# Generated by Django 4.2.2 on 2023-06-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
