name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Osa_05910120
          MYSQL_DATABASE: mydb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"
          
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Display current directory
      run: pwd
      
    - name: List directory contents
      run: ls -al
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --deploy --ignore-pipfile

    - name: Configure MySQL Connection for Django
      run: |
        echo "DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'training-ecommerce',
                'USER': 'testuser',
                'PASSWORD': 'testpass',
                'HOST': '127.0.0.1',
                'PORT': '3306',
            }
        }" >> myproject/settings.py

    - name: Run Tests
      run: |
        pipenv run python manage.py test
