name: Django CI

on:
  push:
    branches:
      - main # Run this workflow on every push to the main branch
  pull_request:
    branches:
      - main # Run this workflow on every pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pipenv install
    - name: Run Tests
      run: |
        python manage.py test
