name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"
          cache: "pip"
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --deploy --ignore-pipfile
      
    - name: Lint with Flake8
      run: |
        flake8 .

    - name: Run Tests
      run: |
        pipenv run python manage.py test
      
